### ISSUE TITLE
Please tag a new release for shairport-sync 3.3.6

### ISSUE THREAD

**Issue by rgov** [Rohmilchkaese/shairport-sync#1]
What do you think about giving your tags names that correspond with the shairport-sync version number? Then it's easier to roll back to an earlier version, or to see what version we are running.

**Comment by Rohmilchkaese** [comment]
Thank you @rgov - you are totally right. I will do that. I also thought about automating builds with Jenkins.

**Comment by rgov** [comment]
GitHub Actions may provide a way to build the packages. Cross platform may require integrating qemu, but I'm sure if it can be done someone has posted a recipe out there. If you figured it out, you could contribute the GitHub pipelines upstream and then there could be an official package.

**Comment by rgov** [comment]
https://github.com/marketplace/actions/docker-buildx

**Comment by rgov** [comment]
I have gotten this 95% working on GitHub Actions, just trying to figure out how to automatically push.

**Comment by Rohmilchkaese** [comment]
This is a really good idea. Thank you very much for your effort. I'm happy to merge your PR #2

**Comment by Rohmilchkaese** [comment]
Thank you for you Work once again @rgov. Will rework that one soon
