### ISSUE TITLE
Use multi-stage build to reduce image size

### ISSUE THREAD

**Issue by rgov** [Rohmilchkaese/shairport-sync#3]
Considering that these images are often deployed on resource-constrained embedded devices, it would be nice to slim down the image further.

I believe that build tools like `automake` and headers from development packages are not needed after the build completes.

Can we figure out what files are actually needed to run? Then we could use a multistage build so that the end product is truly minimal.

```
0x0000ffffb88959c8  0x0000ffffb890fc34  Yes (*)     target:/usr/lib/libasound.so.2
0x0000ffffb884a268  0x0000ffffb884f0f0  Yes (*)     target:/usr/lib/libavahi-common.so.3
0x0000ffffb882a910  0x0000ffffb8831b98  Yes (*)     target:/usr/lib/libavahi-client.so.3
0x0000ffffb87c66e0  0x0000ffffb87dbb90  Yes (*)     target:/usr/lib/libsoxr.so.0
0x0000ffffb865fc90  0x0000ffffb8717b2c  Yes (*)     target:/lib/libcrypto.so.45
0x0000ffffb85dce70  0x0000ffffb85e2964  Yes         target:/usr/local/lib/libalac.so.0
0x0000ffffb85c2350  0x0000ffffb85c69f0  Yes (*)     target:/usr/lib/libconfig.so.11
0x0000ffffb85a7380  0x0000ffffb85acd68  Yes (*)     target:/lib/libpopt.so.0
0x0000ffffb84afe98  0x0000ffffb8541514  Yes (*)     target:/usr/lib/libstdc++.so.6
0x0000ffffb83d1920  0x0000ffffb83dd69c  Yes (*)     target:/usr/lib/libgcc_s.so.1
0x0000ffffb896f2a0  0x0000ffffb89be7a0  Yes (*)     target:/lib/ld-musl-aarch64.so.1
0x0000ffffb83b6dc0  0x0000ffffb83bbccc  Yes (*)     target:/usr/lib/libintl.so.8
0x0000ffffb83688d8  0x0000ffffb83910a0  Yes (*)     target:/usr/lib/libdbus-1.so.3
0x0000ffffb8325b30  0x0000ffffb833f61c  Yes (*)     target:/usr/lib/libgomp.so.1
```

**Comment by Rohmilchkaese** [comment]
I'd be happy reducing the image size more. I guess that `(*)` means that it's needed for the image ?

**Comment by rgov** [comment]
All of those are needed for the `shairport-sync` process. Other processes such as Avahi may require other files and libraries. The `(*)` means there are no debug symbols in the image.

**Comment by rgov** [comment]
Maybe `apk purge` already does a good job of this, I didn't see that before.
