### ISSUE TITLE
Build without debug information

### ISSUE THREAD

**Issue by rgov** [Rohmilchkaese/shairport-sync#4]
Just noticed that `/usr/local/lib/libalac.so.0` is built with debug information. Can it be built as a fully-optimized release build? Is it desirable to have debug information here?

**Comment by Rohmilchkaese** [comment]
You might be right, it probably is possible to build it without debug information. Just need to check/figure out how. If it is possible to do so, I'm happy to update the `Dockerfile` for a fully optimized release build.
